-- Habibi Bites Supabase Database Schema
-- Run this in the Supabase SQL Editor to set up your tables, seeds, and triggers.

-- Drop existing triggers and functions if they exist
DROP TRIGGER IF EXISTS trigger_check_order_capacity_and_delivery ON orders;
DROP FUNCTION IF EXISTS check_order_capacity_and_delivery();

-- Enable uuid extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. Create Settings table
CREATE TABLE IF NOT EXISTS settings (
  id INT PRIMARY KEY,
  delivery_charge_enabled BOOLEAN DEFAULT FALSE,
  delivery_charge_amount NUMERIC DEFAULT 150,
  max_active_orders INT DEFAULT 50,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Create Menu Items table
CREATE TABLE IF NOT EXISTS menu_items (
  id TEXT PRIMARY KEY,
  category TEXT NOT NULL,
  name TEXT NOT NULL,
  description TEXT,
  prices JSONB NOT NULL,
  image TEXT DEFAULT '',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Create Combo Deals table
CREATE TABLE IF NOT EXISTS deals (
  id BIGINT PRIMARY KEY,
  name TEXT NOT NULL,
  tag TEXT DEFAULT '',
  contents TEXT NOT NULL,
  price NUMERIC NOT NULL,
  category TEXT DEFAULT 'Deals',
  image TEXT DEFAULT '',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Create Reviews table
CREATE TABLE IF NOT EXISTS reviews (
  id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  name TEXT NOT NULL,
  rating INT CHECK (rating >= 1 AND rating <= 5),
  comment TEXT,
  date DATE DEFAULT CURRENT_DATE,
  approved BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Create Orders table
CREATE TABLE IF NOT EXISTS orders (
  id TEXT PRIMARY KEY,
  customer JSONB NOT NULL,
  items JSONB NOT NULL,
  total NUMERIC NOT NULL,
  delivery_fee NUMERIC DEFAULT 0,
  status TEXT NOT NULL DEFAULT 'received',
  payment TEXT DEFAULT 'Cash on Delivery',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updates JSONB DEFAULT '[]'::jsonb
);

-- --- Seed Initial Data ---

-- Seed Settings
INSERT INTO settings (id, delivery_charge_enabled, delivery_charge_amount, max_active_orders)
VALUES (1, FALSE, 150, 50)
ON CONFLICT (id) DO NOTHING;

-- Seed default reviews
INSERT INTO reviews (name, rating, comment, date, approved) VALUES
('Hamza Malik', 5, 'Best Zinger burger in Gujranwala! The crunch is absolutely out of this world.', '2026-08-04', TRUE),
('Ayesha Bibi', 4, 'Tikka Pizza was loaded with toppings and steaming hot when delivered. Very impressed!', '2026-08-04', TRUE),
('Zainab Chaudhry', 5, 'The Creamy Habibi Special Pasta has the best cheese pull in the city. A must try!', '2026-08-03', TRUE),
('Usman Ghani', 5, 'Special Deal 7 is super value. The large pizza, burgers and fries easily fed my family.', '2026-08-02', TRUE)
ON CONFLICT DO NOTHING;

-- Seed Menu Items
INSERT INTO menu_items (id, category, name, description, prices, image) VALUES ('pizza_tikka', 'pizza', 'Chicken Tikka Pizza', 'Traditional local chicken tikka pieces, pizza sauce, mozzarella cheese, and fresh onions.', '{"small":550,"regular":1150,"large":1600,"xlarge":2250}'::jsonb, 'assets/pizza_tikka.png') ON CONFLICT (id) DO UPDATE SET category = EXCLUDED.category, name = EXCLUDED.name, description = EXCLUDED.description, prices = EXCLUDED.prices, image = EXCLUDED.image;
INSERT INTO menu_items (id, category, name, description, prices, image) VALUES ('pizza_fajita', 'pizza', 'Chicken Fajita Pizza', 'Fajita style chicken strips, bell peppers, onions, tomatoes, and melting mozzarella.', '{"small":550,"regular":1150,"large":1600,"xlarge":2250}'::jsonb, 'assets/pizza_tikka.png') ON CONFLICT (id) DO UPDATE SET category = EXCLUDED.category, name = EXCLUDED.name, description = EXCLUDED.description, prices = EXCLUDED.prices, image = EXCLUDED.image;
INSERT INTO menu_items (id, category, name, description, prices, image) VALUES ('pizza_malai_boti', 'pizza', 'Malai Boti Pizza', 'Creamy Malai Boti chicken chunks, rich white cream sauce, green chilies, and onions.', '{"small":550,"regular":1150,"large":1600,"xlarge":2250}'::jsonb, 'assets/pizza_tikka.png') ON CONFLICT (id) DO UPDATE SET category = EXCLUDED.category, name = EXCLUDED.name, description = EXCLUDED.description, prices = EXCLUDED.prices, image = EXCLUDED.image;
INSERT INTO menu_items (id, category, name, description, prices, image) VALUES ('pizza_peproni', 'pizza', 'Peproni Pizza', 'Generous layout of premium pepperoni over a rich marinara base with loaded cheese.', '{"small":550,"regular":1150,"large":1600,"xlarge":2250}'::jsonb, 'assets/pizza_tikka.png') ON CONFLICT (id) DO UPDATE SET category = EXCLUDED.category, name = EXCLUDED.name, description = EXCLUDED.description, prices = EXCLUDED.prices, image = EXCLUDED.image;
INSERT INTO menu_items (id, category, name, description, prices, image) VALUES ('pizza_corn_lover', 'pizza', 'Corn Lover Pizza', 'Sweet golden corn kernels, special cream base, sliced black olives, and cheese layer.', '{"small":550,"regular":1150,"large":1600,"xlarge":2250}'::jsonb, 'assets/pizza_tikka.png') ON CONFLICT (id) DO UPDATE SET category = EXCLUDED.category, name = EXCLUDED.name, description = EXCLUDED.description, prices = EXCLUDED.prices, image = EXCLUDED.image;
INSERT INTO menu_items (id, category, name, description, prices, image) VALUES ('pizza_cheese_lover', 'pizza', 'Cheese Lover Pizza', 'A decadent blend of mozzarella, cheddar, and parmesan melted on our herb-crusted house dough.', '{"small":550,"regular":1150,"large":1600,"xlarge":2250}'::jsonb, 'assets/pizza_tikka.png') ON CONFLICT (id) DO UPDATE SET category = EXCLUDED.category, name = EXCLUDED.name, description = EXCLUDED.description, prices = EXCLUDED.prices, image = EXCLUDED.image;
INSERT INTO menu_items (id, category, name, description, prices, image) VALUES ('pizza_supreme', 'pizza', 'Chicken Supreme Pizza', 'Spicy chicken, chicken sausages, bell peppers, mushrooms, black olives, and red onions.', '{"small":550,"regular":1150,"large":1600,"xlarge":2250}'::jsonb, 'assets/pizza_tikka.png') ON CONFLICT (id) DO UPDATE SET category = EXCLUDED.category, name = EXCLUDED.name, description = EXCLUDED.description, prices = EXCLUDED.prices, image = EXCLUDED.image;
INSERT INTO menu_items (id, category, name, description, prices, image) VALUES ('pizza_peri_peri', 'pizza', 'Peri Peri Pizza', 'Spicy peri peri marinated chicken chunks, sliced jalapeños, onions, and hot sauce swirl.', '{"small":550,"regular":1150,"large":1600,"xlarge":2250}'::jsonb, 'assets/pizza_tikka.png') ON CONFLICT (id) DO UPDATE SET category = EXCLUDED.category, name = EXCLUDED.name, description = EXCLUDED.description, prices = EXCLUDED.prices, image = EXCLUDED.image;
INSERT INTO menu_items (id, category, name, description, prices, image) VALUES ('pizza_veg_lover', 'pizza', 'Veg Lover Pizza', 'Fresh mushrooms, sliced tomatoes, bell peppers, sweet corn, black olives, and red onions.', '{"small":550,"regular":1150,"large":1600,"xlarge":2250}'::jsonb, 'assets/pizza_tikka.png') ON CONFLICT (id) DO UPDATE SET category = EXCLUDED.category, name = EXCLUDED.name, description = EXCLUDED.description, prices = EXCLUDED.prices, image = EXCLUDED.image;
INSERT INTO menu_items (id, category, name, description, prices, image) VALUES ('pizza_afghan_tikka', 'pizza', 'Afghan Tikka Pizza', 'Tender Afghan style mild chicken boti, yogurt-based green sauce, onions, and white cheese.', '{"small":550,"regular":1150,"large":1600,"xlarge":2250}'::jsonb, 'assets/pizza_tikka.png') ON CONFLICT (id) DO UPDATE SET category = EXCLUDED.category, name = EXCLUDED.name, description = EXCLUDED.description, prices = EXCLUDED.prices, image = EXCLUDED.image;
INSERT INTO menu_items (id, category, name, description, prices, image) VALUES ('pizza_tandoori', 'pizza', 'Tandoori Pizza', 'Smoky tandoori grilled chicken pieces, traditional tandoori sauce, onions, coriander, and lime juice.', '{"small":550,"regular":1150,"large":1600,"xlarge":2250}'::jsonb, 'assets/pizza_tikka.png') ON CONFLICT (id) DO UPDATE SET category = EXCLUDED.category, name = EXCLUDED.name, description = EXCLUDED.description, prices = EXCLUDED.prices, image = EXCLUDED.image;
INSERT INTO menu_items (id, category, name, description, prices, image) VALUES ('pizza_achari', 'pizza', 'Achari Pizza', 'Tangy pickled chicken pieces, homemade achar sauce, red chilies, and layered mozzarella.', '{"small":550,"regular":1150,"large":1600,"xlarge":2250}'::jsonb, 'assets/pizza_tikka.png') ON CONFLICT (id) DO UPDATE SET category = EXCLUDED.category, name = EXCLUDED.name, description = EXCLUDED.description, prices = EXCLUDED.prices, image = EXCLUDED.image;
INSERT INTO menu_items (id, category, name, description, prices, image) VALUES ('pizza_creamy', 'pizza', 'Creamy Pizza', 'House special rich garlic-cream spread base, loaded with herb chicken boti and green toppings.', '{"small":550,"regular":1150,"large":1600,"xlarge":2250}'::jsonb, 'assets/pizza_tikka.png') ON CONFLICT (id) DO UPDATE SET category = EXCLUDED.category, name = EXCLUDED.name, description = EXCLUDED.description, prices = EXCLUDED.prices, image = EXCLUDED.image;
INSERT INTO menu_items (id, category, name, description, prices, image) VALUES ('pizza_beef_bonanza', 'pizza', 'Beef Bonanza Pizza', 'Minced beef, juicy beef meatball crumbles, bell peppers, red onions, and hot bbq drizzles.', '{"xlarge":2690}'::jsonb, 'assets/pizza_tikka.png') ON CONFLICT (id) DO UPDATE SET category = EXCLUDED.category, name = EXCLUDED.name, description = EXCLUDED.description, prices = EXCLUDED.prices, image = EXCLUDED.image;
INSERT INTO menu_items (id, category, name, description, prices, image) VALUES ('pizza_arabic', 'pizza', 'Habibi Arabic Pizza', 'Arabic spice chicken kebab bits, garlic sauce base, sesame seeds, and green olives.', '{"xlarge":2550}'::jsonb, 'assets/pizza_tikka.png') ON CONFLICT (id) DO UPDATE SET category = EXCLUDED.category, name = EXCLUDED.name, description = EXCLUDED.description, prices = EXCLUDED.prices, image = EXCLUDED.image;
INSERT INTO menu_items (id, category, name, description, prices, image) VALUES ('pizza_4in1', 'pizza', '4 in 1 Special Pizza', 'Four corners, four flavors (Tikka, Fajita, Malai Boti, Pepperoni) on a massive single XL crust.', '{"xlarge":2590}'::jsonb, 'assets/pizza_tikka.png') ON CONFLICT (id) DO UPDATE SET category = EXCLUDED.category, name = EXCLUDED.name, description = EXCLUDED.description, prices = EXCLUDED.prices, image = EXCLUDED.image;
INSERT INTO menu_items (id, category, name, description, prices, image) VALUES ('pizza_donner', 'pizza', 'Habibi Donner Pizza', 'Slices of grilled doner meat, white yogurt sauce, pickles, and crisp sliced onions.', '{"large":1700}'::jsonb, 'assets/pizza_tikka.png') ON CONFLICT (id) DO UPDATE SET category = EXCLUDED.category, name = EXCLUDED.name, description = EXCLUDED.description, prices = EXCLUDED.prices, image = EXCLUDED.image;
INSERT INTO menu_items (id, category, name, description, prices, image) VALUES ('pizza_lasagna', 'pizza', 'Lasagna Pizza', 'Layered flat pasta sheets, Bolognese beef sauce, double béchamel, and rich baked mozzarella crust.', '{"large":1650}'::jsonb, 'assets/pizza_tikka.png') ON CONFLICT (id) DO UPDATE SET category = EXCLUDED.category, name = EXCLUDED.name, description = EXCLUDED.description, prices = EXCLUDED.prices, image = EXCLUDED.image;
INSERT INTO menu_items (id, category, name, description, prices, image) VALUES ('pizza_cheese_steak', 'pizza', 'Cheese Steak Pizza', 'Juicy beef steak strips, caramelized onions, melted cheddar cheese sauce, and bell peppers.', '{"regular":1200,"large":1550}'::jsonb, 'assets/pizza_tikka.png') ON CONFLICT (id) DO UPDATE SET category = EXCLUDED.category, name = EXCLUDED.name, description = EXCLUDED.description, prices = EXCLUDED.prices, image = EXCLUDED.image;
INSERT INTO menu_items (id, category, name, description, prices, image) VALUES ('pizza_crown_crust', 'pizza', 'Crown Crust Pizza', 'Beautifully crimped crust crown-nodes stuffed with cream cheese and topped with grill chicken boti.', '{"large":2000}'::jsonb, 'assets/pizza_tikka.png') ON CONFLICT (id) DO UPDATE SET category = EXCLUDED.category, name = EXCLUDED.name, description = EXCLUDED.description, prices = EXCLUDED.prices, image = EXCLUDED.image;
INSERT INTO menu_items (id, category, name, description, prices, image) VALUES ('pizza_behri_kabab', 'pizza', 'Behari Kabab Crust', 'Spicy Behari chicken kebab stuffed around the rim of the pizza crust, tikka toppings in the center.', '{"large":2150}'::jsonb, 'assets/pizza_tikka.png') ON CONFLICT (id) DO UPDATE SET category = EXCLUDED.category, name = EXCLUDED.name, description = EXCLUDED.description, prices = EXCLUDED.prices, image = EXCLUDED.image;
INSERT INTO menu_items (id, category, name, description, prices, image) VALUES ('pizza_cheese_stuff', 'pizza', 'Cheese Stuff Pizza', 'Stuffed crust loaded with hot melting stringy mozzarella cheese and cheddar cheese blend.', '{"large":2150}'::jsonb, 'assets/pizza_tikka.png') ON CONFLICT (id) DO UPDATE SET category = EXCLUDED.category, name = EXCLUDED.name, description = EXCLUDED.description, prices = EXCLUDED.prices, image = EXCLUDED.image;
INSERT INTO menu_items (id, category, name, description, prices, image) VALUES ('pizza_kabab_stuff', 'pizza', 'Kebab Stuff Pizza', 'Premium chicken seekh kebabs rolled inside the crust borders, loaded with pizza seasonings.', '{"large":2100}'::jsonb, 'assets/pizza_tikka.png') ON CONFLICT (id) DO UPDATE SET category = EXCLUDED.category, name = EXCLUDED.name, description = EXCLUDED.description, prices = EXCLUDED.prices, image = EXCLUDED.image;
INSERT INTO menu_items (id, category, name, description, prices, image) VALUES ('pizza_habibi_grill', 'pizza', 'Habibi Grill Pizza', 'Charcoal grilled chicken thighs, smoked onions, barbecue sauce drizzle, and fresh green bell peppers.', '{"large":2200}'::jsonb, 'assets/pizza_tikka.png') ON CONFLICT (id) DO UPDATE SET category = EXCLUDED.category, name = EXCLUDED.name, description = EXCLUDED.description, prices = EXCLUDED.prices, image = EXCLUDED.image;
INSERT INTO menu_items (id, category, name, description, prices, image) VALUES ('burger_classic_beef', 'burgers', 'Classic Beef Burger', 'Flame-grilled beef patty, fresh lettuce, sliced tomatoes, onions, pickles, and classic burger sauce.', '{"default":580}'::jsonb, 'assets/burger_bomba.png') ON CONFLICT (id) DO UPDATE SET category = EXCLUDED.category, name = EXCLUDED.name, description = EXCLUDED.description, prices = EXCLUDED.prices, image = EXCLUDED.image;
INSERT INTO menu_items (id, category, name, description, prices, image) VALUES ('burger_bomba_beef', 'burgers', 'Bomba Beef Burger', 'Thick double beef patties, loaded with dripping liquid cheddar, crispy onion rings, and spicy bomb sauce.', '{"default":850}'::jsonb, 'assets/burger_bomba.png') ON CONFLICT (id) DO UPDATE SET category = EXCLUDED.category, name = EXCLUDED.name, description = EXCLUDED.description, prices = EXCLUDED.prices, image = EXCLUDED.image;
INSERT INTO menu_items (id, category, name, description, prices, image) VALUES ('burger_jumbo_beef', 'burgers', 'Jumbo Beef Burger', 'Extra large triple-layered beef patties with triple cheese slices, lettuce, fried egg, and special house dressing.', '{"default":1050}'::jsonb, 'assets/burger_bomba.png') ON CONFLICT (id) DO UPDATE SET category = EXCLUDED.category, name = EXCLUDED.name, description = EXCLUDED.description, prices = EXCLUDED.prices, image = EXCLUDED.image;
INSERT INTO menu_items (id, category, name, description, prices, image) VALUES ('burger_zinger', 'burgers', 'Zinger Burger', 'Crispy double-crunch deep fried chicken breast fillet, iceberg lettuce, and high-quality mayo spread.', '{"default":390}'::jsonb, 'assets/burger_bomba.png') ON CONFLICT (id) DO UPDATE SET category = EXCLUDED.category, name = EXCLUDED.name, description = EXCLUDED.description, prices = EXCLUDED.prices, image = EXCLUDED.image;
INSERT INTO menu_items (id, category, name, description, prices, image) VALUES ('burger_petty', 'burgers', 'Petty Burger', 'Traditional breaded fried chicken patty with fresh lettuce and tangy garlic mayo in a soft bun.', '{"default":300}'::jsonb, 'assets/burger_bomba.png') ON CONFLICT (id) DO UPDATE SET category = EXCLUDED.category, name = EXCLUDED.name, description = EXCLUDED.description, prices = EXCLUDED.prices, image = EXCLUDED.image;
INSERT INTO menu_items (id, category, name, description, prices, image) VALUES ('burger_chapli', 'burgers', 'Chapli Burger', 'Spicy pan-fried local style minced beef chapli kabab patty, mint sauce, onion slices, and tomatoes.', '{"default":300}'::jsonb, 'assets/burger_bomba.png') ON CONFLICT (id) DO UPDATE SET category = EXCLUDED.category, name = EXCLUDED.name, description = EXCLUDED.description, prices = EXCLUDED.prices, image = EXCLUDED.image;
INSERT INTO menu_items (id, category, name, description, prices, image) VALUES ('burger_tandoori', 'burgers', 'Tandoori Burger', 'Tandoori coal-grilled chicken breast, spicy tandoori spread, green chutney, and onions.', '{"default":670}'::jsonb, 'assets/burger_bomba.png') ON CONFLICT (id) DO UPDATE SET category = EXCLUDED.category, name = EXCLUDED.name, description = EXCLUDED.description, prices = EXCLUDED.prices, image = EXCLUDED.image;
INSERT INTO menu_items (id, category, name, description, prices, image) VALUES ('burger_pizza', 'burgers', 'Pizza Burger', 'Zinger fillet sandwiched in buns topped with marinara sauce, pizza toppings, and melted baked mozzarella.', '{"default":500}'::jsonb, 'assets/burger_bomba.png') ON CONFLICT (id) DO UPDATE SET category = EXCLUDED.category, name = EXCLUDED.name, description = EXCLUDED.description, prices = EXCLUDED.prices, image = EXCLUDED.image;
INSERT INTO menu_items (id, category, name, description, prices, image) VALUES ('burger_tower', 'burgers', 'Tower Burger', 'Crispy zinger fillet stacked with hash brown patty, cheese slice, lettuce, and tangy burger sauce.', '{"default":650}'::jsonb, 'assets/burger_bomba.png') ON CONFLICT (id) DO UPDATE SET category = EXCLUDED.category, name = EXCLUDED.name, description = EXCLUDED.description, prices = EXCLUDED.prices, image = EXCLUDED.image;
INSERT INTO menu_items (id, category, name, description, prices, image) VALUES ('burger_grill', 'burgers', 'Grill Burger', 'Succulent charcoal grilled chicken thigh with smoky sauce and fresh salad toppers.', '{"single":450,"double":750}'::jsonb, 'assets/burger_bomba.png') ON CONFLICT (id) DO UPDATE SET category = EXCLUDED.category, name = EXCLUDED.name, description = EXCLUDED.description, prices = EXCLUDED.prices, image = EXCLUDED.image;
INSERT INTO menu_items (id, category, name, description, prices, image) VALUES ('wrap_habibi_special', 'wraps', 'Habibi Special Wrap', 'Soft tortilla wrapped with grilled chicken chunks, french fries, cheese sauce, olives, and signature sauce.', '{"default":550}'::jsonb, 'assets/burger_bomba.png') ON CONFLICT (id) DO UPDATE SET category = EXCLUDED.category, name = EXCLUDED.name, description = EXCLUDED.description, prices = EXCLUDED.prices, image = EXCLUDED.image;
INSERT INTO menu_items (id, category, name, description, prices, image) VALUES ('wrap_grill', 'wraps', 'Grill Wrap', 'Smoky grilled chicken strips, shredded lettuce, bell peppers, and creamy chipotle sauce in flatbread.', '{"default":650}'::jsonb, 'assets/burger_bomba.png') ON CONFLICT (id) DO UPDATE SET category = EXCLUDED.category, name = EXCLUDED.name, description = EXCLUDED.description, prices = EXCLUDED.prices, image = EXCLUDED.image;
INSERT INTO menu_items (id, category, name, description, prices, image) VALUES ('shawarma_chicken', 'wraps', 'Chicken Shawarma', 'Local pita bread filled with shredded rotisserie chicken, garlic paste, vinegar pickled cucumber, and cabbage.', '{"default":250}'::jsonb, 'assets/burger_bomba.png') ON CONFLICT (id) DO UPDATE SET category = EXCLUDED.category, name = EXCLUDED.name, description = EXCLUDED.description, prices = EXCLUDED.prices, image = EXCLUDED.image;
INSERT INTO menu_items (id, category, name, description, prices, image) VALUES ('shawarma_zinger', 'wraps', 'Zinger Shawarma', 'Crunchy sliced zinger chicken strips, mayo, and green chili sauce rolled in flat pita bread.', '{"default":390}'::jsonb, 'assets/burger_bomba.png') ON CONFLICT (id) DO UPDATE SET category = EXCLUDED.category, name = EXCLUDED.name, description = EXCLUDED.description, prices = EXCLUDED.prices, image = EXCLUDED.image;
INSERT INTO menu_items (id, category, name, description, prices, image) VALUES ('paratha_chicken', 'wraps', 'Chicken Paratha Roll', 'Golden flaky paratha roll filled with tikka chicken boti, sliced rings of onion, and tangy mint chutney.', '{"default":350}'::jsonb, 'assets/burger_bomba.png') ON CONFLICT (id) DO UPDATE SET category = EXCLUDED.category, name = EXCLUDED.name, description = EXCLUDED.description, prices = EXCLUDED.prices, image = EXCLUDED.image;
INSERT INTO menu_items (id, category, name, description, prices, image) VALUES ('paratha_zinger', 'wraps', 'Zinger Paratha Roll', 'Flaky crisp paratha rolled around deep-fried chicken strips, spicy garlic paste, and onions.', '{"default":430}'::jsonb, 'assets/burger_bomba.png') ON CONFLICT (id) DO UPDATE SET category = EXCLUDED.category, name = EXCLUDED.name, description = EXCLUDED.description, prices = EXCLUDED.prices, image = EXCLUDED.image;
INSERT INTO menu_items (id, category, name, description, prices, image) VALUES ('wrap_malai_boti', 'wraps', 'Malai Boti Wrap', 'Tortilla wrapped with creamy melt-in-the-mouth chicken malai boti chunks and white garlic sauce.', '{"default":590}'::jsonb, 'assets/burger_bomba.png') ON CONFLICT (id) DO UPDATE SET category = EXCLUDED.category, name = EXCLUDED.name, description = EXCLUDED.description, prices = EXCLUDED.prices, image = EXCLUDED.image;
INSERT INTO menu_items (id, category, name, description, prices, image) VALUES ('shawarma_platter', 'wraps', 'Shawarma Platter', 'Deconstructed chicken shawarma served with extra pita bread sides, hummus, pickled veggies, and garlic dip.', '{"default":600}'::jsonb, 'assets/burger_bomba.png') ON CONFLICT (id) DO UPDATE SET category = EXCLUDED.category, name = EXCLUDED.name, description = EXCLUDED.description, prices = EXCLUDED.prices, image = EXCLUDED.image;
INSERT INTO menu_items (id, category, name, description, prices, image) VALUES ('extra_bread', 'wraps', 'Extra Bread (Pita)', 'Warm, freshly baked pita flatbread companion.', '{"default":50}'::jsonb, 'assets/burger_bomba.png') ON CONFLICT (id) DO UPDATE SET category = EXCLUDED.category, name = EXCLUDED.name, description = EXCLUDED.description, prices = EXCLUDED.prices, image = EXCLUDED.image;
INSERT INTO menu_items (id, category, name, description, prices, image) VALUES ('desi_beef_white_karahi', 'desi', 'Beef White Karahi', 'Lean beef chunks slow-cooked in butter, yogurt, cream, fresh ginger, and green chilies.', '{"half_kg":1200,"1_kg":2200}'::jsonb, 'assets/desi_karahi.png') ON CONFLICT (id) DO UPDATE SET category = EXCLUDED.category, name = EXCLUDED.name, description = EXCLUDED.description, prices = EXCLUDED.prices, image = EXCLUDED.image;
INSERT INTO menu_items (id, category, name, description, prices, image) VALUES ('desi_beef_red_karahi', 'desi', 'Beef Red Karahi', 'Traditional spicy tomato-based beef karahi garnished with coriander, ginger, and lime.', '{"half_kg":1200,"1_kg":2200}'::jsonb, 'assets/desi_karahi.png') ON CONFLICT (id) DO UPDATE SET category = EXCLUDED.category, name = EXCLUDED.name, description = EXCLUDED.description, prices = EXCLUDED.prices, image = EXCLUDED.image;
INSERT INTO menu_items (id, category, name, description, prices, image) VALUES ('desi_mutton_karahi', 'desi', 'Mutton Karahi', 'Fresh premium mutton cooked in direct wok with fresh tomatoes, ginger, and freshly cracked black pepper.', '{"half_kg":2200,"1_kg":4200}'::jsonb, 'assets/desi_karahi.png') ON CONFLICT (id) DO UPDATE SET category = EXCLUDED.category, name = EXCLUDED.name, description = EXCLUDED.description, prices = EXCLUDED.prices, image = EXCLUDED.image;
INSERT INTO menu_items (id, category, name, description, prices, image) VALUES ('desi_mutton_peshawari', 'desi', 'Mutton Peshawari Karahi', 'Traditional saltish Peshawari style mutton karahi, cooked with minimal spices and animal fat base.', '{"half_kg":2300,"1_kg":4300}'::jsonb, 'assets/desi_karahi.png') ON CONFLICT (id) DO UPDATE SET category = EXCLUDED.category, name = EXCLUDED.name, description = EXCLUDED.description, prices = EXCLUDED.prices, image = EXCLUDED.image;
INSERT INTO menu_items (id, category, name, description, prices, image) VALUES ('desi_mutton_irani', 'desi', 'Mutton Irani Karahi', 'Rich mild mutton gravy prepared with cashew paste, cream, saffron hints, and white butter.', '{"half_kg":2350,"1_kg":4400}'::jsonb, 'assets/desi_karahi.png') ON CONFLICT (id) DO UPDATE SET category = EXCLUDED.category, name = EXCLUDED.name, description = EXCLUDED.description, prices = EXCLUDED.prices, image = EXCLUDED.image;
INSERT INTO menu_items (id, category, name, description, prices, image) VALUES ('desi_mutton_sulemani', 'desi', 'Mutton Sulemani Karahi', 'Herby mutton karahi cooked with green chilies, black pepper, and lemon slices. Light on spices.', '{"half_kg":2250,"1_kg":4250}'::jsonb, 'assets/desi_karahi.png') ON CONFLICT (id) DO UPDATE SET category = EXCLUDED.category, name = EXCLUDED.name, description = EXCLUDED.description, prices = EXCLUDED.prices, image = EXCLUDED.image;
INSERT INTO menu_items (id, category, name, description, prices, image) VALUES ('desi_chicken_white_handi', 'desi', 'Chicken White Handi', 'Boneless chicken cubes simmered in a clay handi with rich almond cream sauce and white pepper.', '{"half_kg":1400,"1_kg":2200}'::jsonb, 'assets/desi_karahi.png') ON CONFLICT (id) DO UPDATE SET category = EXCLUDED.category, name = EXCLUDED.name, description = EXCLUDED.description, prices = EXCLUDED.prices, image = EXCLUDED.image;
INSERT INTO menu_items (id, category, name, description, prices, image) VALUES ('desi_chicken_achari_handi', 'desi', 'Chicken Achari Handi', 'Spicy boneless chicken simmered with local pickled spices, mustard seeds, and ginger strips.', '{"half_kg":1400,"1_kg":2200}'::jsonb, 'assets/desi_karahi.png') ON CONFLICT (id) DO UPDATE SET category = EXCLUDED.category, name = EXCLUDED.name, description = EXCLUDED.description, prices = EXCLUDED.prices, image = EXCLUDED.image;
INSERT INTO menu_items (id, category, name, description, prices, image) VALUES ('desi_chicken_malai_handi', 'desi', 'Chicken Malai Handi', 'Ultra-smooth cream gravy cooked in clay handi with cardamom infused chicken cubes.', '{"half_kg":1400,"1_kg":2200}'::jsonb, 'assets/desi_karahi.png') ON CONFLICT (id) DO UPDATE SET category = EXCLUDED.category, name = EXCLUDED.name, description = EXCLUDED.description, prices = EXCLUDED.prices, image = EXCLUDED.image;
INSERT INTO menu_items (id, category, name, description, prices, image) VALUES ('desi_chicken_jaipoori', 'desi', 'Chicken Jaipoori Handi', 'Rajasthani style rich spicy gravy cooked with fried onions, crushed nuts, and special spice blend.', '{"half_kg":1550}'::jsonb, 'assets/desi_karahi.png') ON CONFLICT (id) DO UPDATE SET category = EXCLUDED.category, name = EXCLUDED.name, description = EXCLUDED.description, prices = EXCLUDED.prices, image = EXCLUDED.image;
INSERT INTO menu_items (id, category, name, description, prices, image) VALUES ('desi_chicken_red_handi', 'desi', 'Chicken Red Handi', 'Boneless chicken breast strips cooked in clay handi with tomatoes, garlic paste, and local spices.', '{"half_kg":1400,"1_kg":2200}'::jsonb, 'assets/desi_karahi.png') ON CONFLICT (id) DO UPDATE SET category = EXCLUDED.category, name = EXCLUDED.name, description = EXCLUDED.description, prices = EXCLUDED.prices, image = EXCLUDED.image;
INSERT INTO menu_items (id, category, name, description, prices, image) VALUES ('desi_chicken_white_karahi', 'desi', 'Chicken White Karahi', 'Wok-fried chicken bone-in portions simmered in thick yogurt, white pepper, and green chilies.', '{"half_kg":1400,"1_kg":2200}'::jsonb, 'assets/desi_karahi.png') ON CONFLICT (id) DO UPDATE SET category = EXCLUDED.category, name = EXCLUDED.name, description = EXCLUDED.description, prices = EXCLUDED.prices, image = EXCLUDED.image;
INSERT INTO menu_items (id, category, name, description, prices, image) VALUES ('desi_chicken_peshawari', 'desi', 'Chicken Peshawari Karahi', 'Traditional salt-cured chicken cooked with sliced tomatoes, green peppers, and black seed highlights.', '{"half_kg":1600,"1_kg":2350}'::jsonb, 'assets/desi_karahi.png') ON CONFLICT (id) DO UPDATE SET category = EXCLUDED.category, name = EXCLUDED.name, description = EXCLUDED.description, prices = EXCLUDED.prices, image = EXCLUDED.image;
INSERT INTO menu_items (id, category, name, description, prices, image) VALUES ('desi_chicken_red_karahi', 'desi', 'Chicken Red Karahi', 'Spicy tomato gravy karahi prepared with bone-in chicken, green coriander, and fresh julienned ginger.', '{"half_kg":1550,"1_kg":2200}'::jsonb, 'assets/desi_karahi.png') ON CONFLICT (id) DO UPDATE SET category = EXCLUDED.category, name = EXCLUDED.name, description = EXCLUDED.description, prices = EXCLUDED.prices, image = EXCLUDED.image;
INSERT INTO menu_items (id, category, name, description, prices, image) VALUES ('broast_quarter', 'desi', 'Quarter Broast (Spicy)', '1 Leg, 1 Thigh piece crispy fried, served with hot golden French fries, 1 bun, garlic dip, and 1 regular drink.', '{"default":650}'::jsonb, 'assets/desi_karahi.png') ON CONFLICT (id) DO UPDATE SET category = EXCLUDED.category, name = EXCLUDED.name, description = EXCLUDED.description, prices = EXCLUDED.prices, image = EXCLUDED.image;
INSERT INTO menu_items (id, category, name, description, prices, image) VALUES ('broast_half', 'desi', 'Half Broast (Spicy)', '2 Leg, 2 Thigh crispy golden broast pieces, fries, 1 soft bun, garlic dip, fries dip, and 1 regular drink.', '{"default":1090}'::jsonb, 'assets/desi_karahi.png') ON CONFLICT (id) DO UPDATE SET category = EXCLUDED.category, name = EXCLUDED.name, description = EXCLUDED.description, prices = EXCLUDED.prices, image = EXCLUDED.image;
INSERT INTO menu_items (id, category, name, description, prices, image) VALUES ('broast_full', 'desi', 'Full Broast (Spicy)', '4 Leg, 4 Thigh giant broast platter, double fries portions, 2 soft buns, 2 garlic dips, 2 fries dips, and 1.5 Ltr cold drink.', '{"default":2150}'::jsonb, 'assets/desi_karahi.png') ON CONFLICT (id) DO UPDATE SET category = EXCLUDED.category, name = EXCLUDED.name, description = EXCLUDED.description, prices = EXCLUDED.prices, image = EXCLUDED.image;
INSERT INTO menu_items (id, category, name, description, prices, image) VALUES ('side_nuggets', 'starters', 'Chicken Nuggets', 'Tender white chicken bites breaded and fried golden crisp, served with ketchup dip.', '{"6_pcs":350,"12_pcs":550}'::jsonb, 'assets/starters_loaded_fries.png') ON CONFLICT (id) DO UPDATE SET category = EXCLUDED.category, name = EXCLUDED.name, description = EXCLUDED.description, prices = EXCLUDED.prices, image = EXCLUDED.image;
INSERT INTO menu_items (id, category, name, description, prices, image) VALUES ('side_wings', 'starters', 'Oven Baked Wings', 'Juicy chicken wings coated in spicy hot buffalo sauce and baked slowly in the brick oven.', '{"6_pcs":500,"12_pcs":1000}'::jsonb, 'assets/starters_loaded_fries.png') ON CONFLICT (id) DO UPDATE SET category = EXCLUDED.category, name = EXCLUDED.name, description = EXCLUDED.description, prices = EXCLUDED.prices, image = EXCLUDED.image;
INSERT INTO menu_items (id, category, name, description, prices, image) VALUES ('side_strips', 'starters', 'Chicken Strips', 'Breaded boneless chicken breast fingers fried crispy, served with garlic mayo sauce.', '{"5_pcs":500,"10_pcs":900}'::jsonb, 'assets/starters_loaded_fries.png') ON CONFLICT (id) DO UPDATE SET category = EXCLUDED.category, name = EXCLUDED.name, description = EXCLUDED.description, prices = EXCLUDED.prices, image = EXCLUDED.image;
INSERT INTO menu_items (id, category, name, description, prices, image) VALUES ('side_loaded_fries', 'starters', 'Loaded Fries', 'Crispy french fries topped with sliced chicken strips, hot liquid cheese sauce, and green jalapeños.', '{"medium":550,"large":690}'::jsonb, 'assets/starters_loaded_fries.png') ON CONFLICT (id) DO UPDATE SET category = EXCLUDED.category, name = EXCLUDED.name, description = EXCLUDED.description, prices = EXCLUDED.prices, image = EXCLUDED.image;
INSERT INTO menu_items (id, category, name, description, prices, image) VALUES ('side_french_fries', 'starters', 'French Fries', 'Crisp salted potato fries, soft inside and crunchy on the borders.', '{"medium":350,"large":550}'::jsonb, 'assets/starters_loaded_fries.png') ON CONFLICT (id) DO UPDATE SET category = EXCLUDED.category, name = EXCLUDED.name, description = EXCLUDED.description, prices = EXCLUDED.prices, image = EXCLUDED.image;
INSERT INTO menu_items (id, category, name, description, prices, image) VALUES ('sandwich_habibi_special', 'starters', 'Habibi Special Sandwich', 'Multi-layered club sandwich filled with grilled chicken, cheese slice, omelette, sliced tomatoes, cucumbers, and special spread.', '{"default":650}'::jsonb, 'assets/starters_loaded_fries.png') ON CONFLICT (id) DO UPDATE SET category = EXCLUDED.category, name = EXCLUDED.name, description = EXCLUDED.description, prices = EXCLUDED.prices, image = EXCLUDED.image;
INSERT INTO menu_items (id, category, name, description, prices, image) VALUES ('sandwich_grill', 'starters', 'Grill Sandwich', 'Panini grilled bread filled with shredded bbq chicken thighs, melting cheddar cheese, and capsicums.', '{"default":650}'::jsonb, 'assets/starters_loaded_fries.png') ON CONFLICT (id) DO UPDATE SET category = EXCLUDED.category, name = EXCLUDED.name, description = EXCLUDED.description, prices = EXCLUDED.prices, image = EXCLUDED.image;
INSERT INTO menu_items (id, category, name, description, prices, image) VALUES ('sandwich_club', 'starters', 'Club Sandwich', 'Traditional toasted bread sandwich with chicken salad spread, hard-boiled egg slices, and lettuce layers.', '{"default":550}'::jsonb, 'assets/starters_loaded_fries.png') ON CONFLICT (id) DO UPDATE SET category = EXCLUDED.category, name = EXCLUDED.name, description = EXCLUDED.description, prices = EXCLUDED.prices, image = EXCLUDED.image;
INSERT INTO menu_items (id, category, name, description, prices, image) VALUES ('sandwich_cold_chicken', 'starters', 'Cold Chicken Sandwich', 'Soft chilled bread slices stuffed with finely shredded chicken salad and black pepper mayo.', '{"default":500}'::jsonb, 'assets/starters_loaded_fries.png') ON CONFLICT (id) DO UPDATE SET category = EXCLUDED.category, name = EXCLUDED.name, description = EXCLUDED.description, prices = EXCLUDED.prices, image = EXCLUDED.image;
INSERT INTO menu_items (id, category, name, description, prices, image) VALUES ('sandwich_cold_veg', 'starters', 'Veg Cold Sandwich', 'Toasted sandwich with layers of fresh cucumbers, tomatoes, carrots, cabbage, and light diet dressing.', '{"default":480}'::jsonb, 'assets/starters_loaded_fries.png') ON CONFLICT (id) DO UPDATE SET category = EXCLUDED.category, name = EXCLUDED.name, description = EXCLUDED.description, prices = EXCLUDED.prices, image = EXCLUDED.image;
INSERT INTO menu_items (id, category, name, description, prices, image) VALUES ('sandwich_zinger', 'starters', 'Zinger Sandwich', 'Submarine roll filled with crispy zinger chicken chunks, lettuce, and premium garlic mayonnaise.', '{"default":550}'::jsonb, 'assets/starters_loaded_fries.png') ON CONFLICT (id) DO UPDATE SET category = EXCLUDED.category, name = EXCLUDED.name, description = EXCLUDED.description, prices = EXCLUDED.prices, image = EXCLUDED.image;
INSERT INTO menu_items (id, category, name, description, prices, image) VALUES ('salad_fattoush', 'starters', 'Fattoush Salad', 'Traditional Levantine salad made of toasted pita croutons, mixed greens, radishes, tomatoes, cucumbers, and olive oil.', '{"default":580}'::jsonb, 'assets/starters_loaded_fries.png') ON CONFLICT (id) DO UPDATE SET category = EXCLUDED.category, name = EXCLUDED.name, description = EXCLUDED.description, prices = EXCLUDED.prices, image = EXCLUDED.image;
INSERT INTO menu_items (id, category, name, description, prices, image) VALUES ('salad_fattoush_chicken', 'starters', 'Fattoush with Grilled Chicken', 'Our signature Fattoush salad topped with tender sliced charcoal-grilled chicken breast pieces.', '{"default":780}'::jsonb, 'assets/starters_loaded_fries.png') ON CONFLICT (id) DO UPDATE SET category = EXCLUDED.category, name = EXCLUDED.name, description = EXCLUDED.description, prices = EXCLUDED.prices, image = EXCLUDED.image;
INSERT INTO menu_items (id, category, name, description, prices, image) VALUES ('salad_russian', 'starters', 'Special Russian Salad', 'Chilled combination of diced apples, pineapples, sweet peas, potatoes, carrots in sweet cream salad sauce.', '{"default":270}'::jsonb, 'assets/starters_loaded_fries.png') ON CONFLICT (id) DO UPDATE SET category = EXCLUDED.category, name = EXCLUDED.name, description = EXCLUDED.description, prices = EXCLUDED.prices, image = EXCLUDED.image;
INSERT INTO menu_items (id, category, name, description, prices, image) VALUES ('salad_chana_chaat', 'starters', 'Chana Chaat', 'Spicy chickpea salad mixed with raw onions, chopped tomatoes, green chilies, yogurt, and sweet-sour tamarind syrup.', '{"default":270}'::jsonb, 'assets/starters_loaded_fries.png') ON CONFLICT (id) DO UPDATE SET category = EXCLUDED.category, name = EXCLUDED.name, description = EXCLUDED.description, prices = EXCLUDED.prices, image = EXCLUDED.image;
INSERT INTO menu_items (id, category, name, description, prices, image) VALUES ('pasta_alfredo', 'pasta', 'Alfredo Pasta', 'Fettuccine pasta tossed in butter-parmesan cream sauce, topped with grilled chicken breast slices and mushrooms.', '{"medium":650,"large":900}'::jsonb, 'assets/starters_loaded_fries.png') ON CONFLICT (id) DO UPDATE SET category = EXCLUDED.category, name = EXCLUDED.name, description = EXCLUDED.description, prices = EXCLUDED.prices, image = EXCLUDED.image;
INSERT INTO menu_items (id, category, name, description, prices, image) VALUES ('pasta_creamy_special', 'pasta', 'Creamy Habibi Special Pasta', 'Penne pasta cooked in white spicy herb cream sauce, loaded with bell peppers, olives, chicken chunks, and baked cheese cover.', '{"medium":600,"large":850}'::jsonb, 'assets/starters_loaded_fries.png') ON CONFLICT (id) DO UPDATE SET category = EXCLUDED.category, name = EXCLUDED.name, description = EXCLUDED.description, prices = EXCLUDED.prices, image = EXCLUDED.image;
INSERT INTO menu_items (id, category, name, description, prices, image) VALUES ('pasta_penny_sauce', 'pasta', 'Penny Sauce Pasta', 'Penne pasta cooked in spicy red marinara and white cream mix (pink sauce), roasted garlic, chicken, and broccoli.', '{"medium":450,"large":690}'::jsonb, 'assets/starters_loaded_fries.png') ON CONFLICT (id) DO UPDATE SET category = EXCLUDED.category, name = EXCLUDED.name, description = EXCLUDED.description, prices = EXCLUDED.prices, image = EXCLUDED.image;
INSERT INTO menu_items (id, category, name, description, prices, image) VALUES ('pasta_macaroni', 'pasta', 'Chicken Macaronies Pasta', 'Elbow macaroni stir-fried in local desified wok style with chicken chunks, capsicums, cabbage, carrots, soy sauce, and chilies.', '{"medium":400,"large":650}'::jsonb, 'assets/starters_loaded_fries.png') ON CONFLICT (id) DO UPDATE SET category = EXCLUDED.category, name = EXCLUDED.name, description = EXCLUDED.description, prices = EXCLUDED.prices, image = EXCLUDED.image;
INSERT INTO menu_items (id, category, name, description, prices, image) VALUES ('shake_mango', 'drinks', 'Mango Ice Shake', 'Creamy milkshake blended with sweet mango pulp, vanilla ice cream, and chilled fresh milk.', '{"default":480}'::jsonb, 'assets/hero_food_collage.png') ON CONFLICT (id) DO UPDATE SET category = EXCLUDED.category, name = EXCLUDED.name, description = EXCLUDED.description, prices = EXCLUDED.prices, image = EXCLUDED.image;
INSERT INTO menu_items (id, category, name, description, prices, image) VALUES ('shake_strawberry', 'drinks', 'Strawberry Ice Shake', 'Vibrant pink milkshake blended with sweet strawberries, strawberry ice cream scoop, and fresh cream.', '{"default":480}'::jsonb, 'assets/hero_food_collage.png') ON CONFLICT (id) DO UPDATE SET category = EXCLUDED.category, name = EXCLUDED.name, description = EXCLUDED.description, prices = EXCLUDED.prices, image = EXCLUDED.image;
INSERT INTO menu_items (id, category, name, description, prices, image) VALUES ('shake_kulfi', 'drinks', 'Kulfi Ice Shake', 'Traditional local shake containing crushed khoya kulfi pieces, almond nuts, cardamom, and thick milk.', '{"default":480}'::jsonb, 'assets/hero_food_collage.png') ON CONFLICT (id) DO UPDATE SET category = EXCLUDED.category, name = EXCLUDED.name, description = EXCLUDED.description, prices = EXCLUDED.prices, image = EXCLUDED.image;
INSERT INTO menu_items (id, category, name, description, prices, image) VALUES ('shake_oreo', 'drinks', 'Oreo Ice Shake', 'Indulgent shake containing crushed chocolate Oreo cookies, vanilla-chocolate ice cream, and chocolate fudge syrup.', '{"default":520}'::jsonb, 'assets/hero_food_collage.png') ON CONFLICT (id) DO UPDATE SET category = EXCLUDED.category, name = EXCLUDED.name, description = EXCLUDED.description, prices = EXCLUDED.prices, image = EXCLUDED.image;
INSERT INTO menu_items (id, category, name, description, prices, image) VALUES ('drink_margarita', 'drinks', 'Mint Margarita', 'Refreshing soda blend with freshly squeezed lemon juice, crushed mint leaves, salt, sugar, and ice.', '{"default":220}'::jsonb, 'assets/hero_food_collage.png') ON CONFLICT (id) DO UPDATE SET category = EXCLUDED.category, name = EXCLUDED.name, description = EXCLUDED.description, prices = EXCLUDED.prices, image = EXCLUDED.image;
INSERT INTO menu_items (id, category, name, description, prices, image) VALUES ('drink_sprite_lime', 'drinks', 'Sprite Lime', 'Carbonated lemon-lime soda enhanced with freshly squeezed lime juice and a dash of black salt.', '{"default":200}'::jsonb, 'assets/hero_food_collage.png') ON CONFLICT (id) DO UPDATE SET category = EXCLUDED.category, name = EXCLUDED.name, description = EXCLUDED.description, prices = EXCLUDED.prices, image = EXCLUDED.image;
INSERT INTO menu_items (id, category, name, description, prices, image) VALUES ('icecream_chocolate_vanilla', 'drinks', 'Chocolate Vanilla Ice Cream', 'Three rich scoops of marbled premium chocolate and smooth vanilla ice cream.', '{"default":380}'::jsonb, 'assets/hero_food_collage.png') ON CONFLICT (id) DO UPDATE SET category = EXCLUDED.category, name = EXCLUDED.name, description = EXCLUDED.description, prices = EXCLUDED.prices, image = EXCLUDED.image;
INSERT INTO menu_items (id, category, name, description, prices, image) VALUES ('icecream_mango_vanilla', 'drinks', 'Mango Vanilla Ice Cream', 'Three delicious scoops of mango and vanilla flavored ice cream blend.', '{"default":380}'::jsonb, 'assets/hero_food_collage.png') ON CONFLICT (id) DO UPDATE SET category = EXCLUDED.category, name = EXCLUDED.name, description = EXCLUDED.description, prices = EXCLUDED.prices, image = EXCLUDED.image;
INSERT INTO menu_items (id, category, name, description, prices, image) VALUES ('icecream_strawberry_vanilla', 'drinks', 'Strawberry Vanilla Ice Cream', 'Three creamy scoops featuring strawberry and vanilla flavors, topped with sweet syrup.', '{"default":380}'::jsonb, 'assets/hero_food_collage.png') ON CONFLICT (id) DO UPDATE SET category = EXCLUDED.category, name = EXCLUDED.name, description = EXCLUDED.description, prices = EXCLUDED.prices, image = EXCLUDED.image;
INSERT INTO menu_items (id, category, name, description, prices, image) VALUES ('icecream_kulfi', 'drinks', 'Kulfi Ice Cream (3 Scoop)', 'Traditional desi kulfi flavored ice cream scoops topped with pistachio shavings.', '{"default":380}'::jsonb, 'assets/hero_food_collage.png') ON CONFLICT (id) DO UPDATE SET category = EXCLUDED.category, name = EXCLUDED.name, description = EXCLUDED.description, prices = EXCLUDED.prices, image = EXCLUDED.image;
INSERT INTO menu_items (id, category, name, description, prices, image) VALUES ('icecream_mango', 'drinks', 'Mango Ice Cream (3 Scoop)', 'Three scoops of luscious sweet mango seasonal fruit flavor ice cream.', '{"default":380}'::jsonb, 'assets/hero_food_collage.png') ON CONFLICT (id) DO UPDATE SET category = EXCLUDED.category, name = EXCLUDED.name, description = EXCLUDED.description, prices = EXCLUDED.prices, image = EXCLUDED.image;
INSERT INTO menu_items (id, category, name, description, prices, image) VALUES ('icecream_tutti_frutti', 'drinks', 'Tutti Frutti Ice Cream (3 Scoop)', 'Creamy colorful scoops containing candy candied-fruit bits (ashrafi) and dry nut crunch.', '{"default":380}'::jsonb, 'assets/hero_food_collage.png') ON CONFLICT (id) DO UPDATE SET category = EXCLUDED.category, name = EXCLUDED.name, description = EXCLUDED.description, prices = EXCLUDED.prices, image = EXCLUDED.image;
INSERT INTO menu_items (id, category, name, description, prices, image) VALUES ('icecream_strawberry', 'drinks', 'Strawberry Ice Cream (3 Scoop)', 'Three scoops of creamy pink strawberry flavored ice cream.', '{"default":380}'::jsonb, 'assets/hero_food_collage.png') ON CONFLICT (id) DO UPDATE SET category = EXCLUDED.category, name = EXCLUDED.name, description = EXCLUDED.description, prices = EXCLUDED.prices, image = EXCLUDED.image;
INSERT INTO menu_items (id, category, name, description, prices, image) VALUES ('icecream_oreo', 'drinks', 'Oreo Ice Cream (3 Scoop)', 'Cookies and cream flavored scoops mixed with chunky pieces of sweet Oreo biscuits.', '{"default":380}'::jsonb, 'assets/hero_food_collage.png') ON CONFLICT (id) DO UPDATE SET category = EXCLUDED.category, name = EXCLUDED.name, description = EXCLUDED.description, prices = EXCLUDED.prices, image = EXCLUDED.image;
INSERT INTO menu_items (id, category, name, description, prices, image) VALUES ('icecream_coconut', 'drinks', 'Coconut Ice Cream (3 Scoop)', 'Subtle coconut cream flavored scoops sprinkled with desiccated raw coconut shreds.', '{"default":380}'::jsonb, 'assets/hero_food_collage.png') ON CONFLICT (id) DO UPDATE SET category = EXCLUDED.category, name = EXCLUDED.name, description = EXCLUDED.description, prices = EXCLUDED.prices, image = EXCLUDED.image;
INSERT INTO menu_items (id, category, name, description, prices, image) VALUES ('icecream_pistachio', 'drinks', 'Pistachio Ice Cream (3 Scoop)', 'Light green aromatic pistachio nut flavored ice cream scoops.', '{"default":380}'::jsonb, 'assets/hero_food_collage.png') ON CONFLICT (id) DO UPDATE SET category = EXCLUDED.category, name = EXCLUDED.name, description = EXCLUDED.description, prices = EXCLUDED.prices, image = EXCLUDED.image;
INSERT INTO menu_items (id, category, name, description, prices, image) VALUES ('hot_tea', 'drinks', 'Habibi Special Tea (Karak)', 'Brewed with high-quality cardamom tea leaves, fresh thick milk, and sugar simmered slowly.', '{"default":130}'::jsonb, 'assets/hero_food_collage.png') ON CONFLICT (id) DO UPDATE SET category = EXCLUDED.category, name = EXCLUDED.name, description = EXCLUDED.description, prices = EXCLUDED.prices, image = EXCLUDED.image;
INSERT INTO menu_items (id, category, name, description, prices, image) VALUES ('hot_coffee', 'drinks', 'Hot Coffee', 'Strong aromatic espresso shot combined with steamed milk froth.', '{"default":380}'::jsonb, 'assets/hero_food_collage.png') ON CONFLICT (id) DO UPDATE SET category = EXCLUDED.category, name = EXCLUDED.name, description = EXCLUDED.description, prices = EXCLUDED.prices, image = EXCLUDED.image;

-- Seed Combo Deals
INSERT INTO deals (id, name, tag, contents, price, category, image) VALUES (1, 'Habibi Deal 1', 'Hot Seller', '2 Small Pizzas + 1 Ltr Cold Drink', 1150, 'Deals', 'assets/pizza_tikka.png') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, tag = EXCLUDED.tag, contents = EXCLUDED.contents, price = EXCLUDED.price, category = EXCLUDED.category, image = EXCLUDED.image;
INSERT INTO deals (id, name, tag, contents, price, category, image) VALUES (2, 'Habibi Deal 2', 'Popular', '1 Medium Pizza + 6 Hot Wings + 1 Ltr Cold Drink', 1700, 'Deals', 'assets/pizza_tikka.png') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, tag = EXCLUDED.tag, contents = EXCLUDED.contents, price = EXCLUDED.price, category = EXCLUDED.category, image = EXCLUDED.image;
INSERT INTO deals (id, name, tag, contents, price, category, image) VALUES (3, 'Habibi Deal 3', 'Super Value', '1 Medium Pizza + 12 Hot Wings + 1.5 Ltr Cold Drink', 2200, 'Deals', 'assets/pizza_tikka.png') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, tag = EXCLUDED.tag, contents = EXCLUDED.contents, price = EXCLUDED.price, category = EXCLUDED.category, image = EXCLUDED.image;
INSERT INTO deals (id, name, tag, contents, price, category, image) VALUES (4, 'Habibi Deal 4', 'New', '1 Medium Pizza + 1 Cheese Stick + 1.5 Ltr Cold Drink', 2400, 'Deals', 'assets/pizza_tikka.png') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, tag = EXCLUDED.tag, contents = EXCLUDED.contents, price = EXCLUDED.price, category = EXCLUDED.category, image = EXCLUDED.image;
INSERT INTO deals (id, name, tag, contents, price, category, image) VALUES (5, 'Habibi Deal 5', 'Mega Feast', '1 Large Pizza + 6 Hot Wings + 1.5 Ltr Cold Drink', 2580, 'Deals', 'assets/pizza_tikka.png') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, tag = EXCLUDED.tag, contents = EXCLUDED.contents, price = EXCLUDED.price, category = EXCLUDED.category, image = EXCLUDED.image;
INSERT INTO deals (id, name, tag, contents, price, category, image) VALUES (6, 'Habibi Deal 6', 'Jumbo Deal', '1 Large Pizza + 4 Regular Zinger Burgers + 1.5 Ltr Cold Drink', 3250, 'Deals', 'assets/hero_food_collage.png') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, tag = EXCLUDED.tag, contents = EXCLUDED.contents, price = EXCLUDED.price, category = EXCLUDED.category, image = EXCLUDED.image;
INSERT INTO deals (id, name, tag, contents, price, category, image) VALUES (7, 'Habibi Deal 7', 'Party Special', '1 Large Pizza + 2 Zinger Burgers + 1 Regular Fries + 1.5 Ltr Cold Drink', 2850, 'Deals', 'assets/hero_food_collage.png') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, tag = EXCLUDED.tag, contents = EXCLUDED.contents, price = EXCLUDED.price, category = EXCLUDED.category, image = EXCLUDED.image;
INSERT INTO deals (id, name, tag, contents, price, category, image) VALUES (8, 'Habibi Deal 8', 'Crowd Pleaser', '2 Medium Pizzas + 1 Regular Zinger Burger + 1 Regular Fries + 1.5 Ltr Cold Drink', 3100, 'Deals', 'assets/hero_food_collage.png') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, tag = EXCLUDED.tag, contents = EXCLUDED.contents, price = EXCLUDED.price, category = EXCLUDED.category, image = EXCLUDED.image;
INSERT INTO deals (id, name, tag, contents, price, category, image) VALUES (9, 'Habibi Deal 9', 'Giant Deal', '2 Extra Large (XL) Pizzas + 1 Regular Fries + 1.5 Ltr Cold Drink', 4850, 'Deals', 'assets/pizza_tikka.png') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, tag = EXCLUDED.tag, contents = EXCLUDED.contents, price = EXCLUDED.price, category = EXCLUDED.category, image = EXCLUDED.image;
INSERT INTO deals (id, name, tag, contents, price, category, image) VALUES (10, 'Habibi Deal 10', 'Individual Saver', '1 Regular Zinger Burger + 1 Regular Fries + 1 Regular Drink', 650, 'Deals', 'assets/burger_bomba.png') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, tag = EXCLUDED.tag, contents = EXCLUDED.contents, price = EXCLUDED.price, category = EXCLUDED.category, image = EXCLUDED.image;
INSERT INTO deals (id, name, tag, contents, price, category, image) VALUES (11, 'Habibi Deal 11', 'Duet Offer', '2 Cheese Patty Burgers + 2 Regular Drinks', 750, 'Deals', 'assets/burger_bomba.png') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, tag = EXCLUDED.tag, contents = EXCLUDED.contents, price = EXCLUDED.price, category = EXCLUDED.category, image = EXCLUDED.image;
INSERT INTO deals (id, name, tag, contents, price, category, image) VALUES (12, 'Habibi Deal 12', 'Zinger Bundle', '2 Regular Zinger Burgers + 1 Regular Fries + 2 Regular Drinks', 1050, 'Deals', 'assets/burger_bomba.png') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, tag = EXCLUDED.tag, contents = EXCLUDED.contents, price = EXCLUDED.price, category = EXCLUDED.category, image = EXCLUDED.image;
INSERT INTO deals (id, name, tag, contents, price, category, image) VALUES (13, 'Habibi Deal 13', 'Shawarma Combo', '3 Chicken Shawarmas + 1 Ltr Cold Drink', 800, 'Deals', 'assets/burger_bomba.png') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, tag = EXCLUDED.tag, contents = EXCLUDED.contents, price = EXCLUDED.price, category = EXCLUDED.category, image = EXCLUDED.image;
INSERT INTO deals (id, name, tag, contents, price, category, image) VALUES (14, 'Habibi Deal 14', 'Zinger Craze', '4 Regular Zinger Burgers + 1.5 Ltr Cold Drink', 1950, 'Deals', 'assets/burger_bomba.png') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, tag = EXCLUDED.tag, contents = EXCLUDED.contents, price = EXCLUDED.price, category = EXCLUDED.category, image = EXCLUDED.image;
INSERT INTO deals (id, name, tag, contents, price, category, image) VALUES (15, 'Habibi Deal 15', 'Family Pack', '6 Regular Burgers + 12 Pieces Chicken Nuggets + 1.5 Ltr Cold Drink', 2250, 'Deals', 'assets/hero_food_collage.png') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, tag = EXCLUDED.tag, contents = EXCLUDED.contents, price = EXCLUDED.price, category = EXCLUDED.category, image = EXCLUDED.image;
INSERT INTO deals (id, name, tag, contents, price, category, image) VALUES (16, 'Habibi Deal 16', 'Double Fun', '2 Large Pizzas + 1.5 Ltr Cold Drink', 3150, 'Deals', 'assets/pizza_tikka.png') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, tag = EXCLUDED.tag, contents = EXCLUDED.contents, price = EXCLUDED.price, category = EXCLUDED.category, image = EXCLUDED.image;
INSERT INTO deals (id, name, tag, contents, price, category, image) VALUES (17, 'Habibi Deal 17', 'Beef Saver', '1 Beef Burger + 1 Regular Fries + 1 Regular Drink', 880, 'Deals', 'assets/burger_bomba.png') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, tag = EXCLUDED.tag, contents = EXCLUDED.contents, price = EXCLUDED.price, category = EXCLUDED.category, image = EXCLUDED.image;
INSERT INTO deals (id, name, tag, contents, price, category, image) VALUES (18, 'Habibi Deal 18', 'Beef Bundle', '2 Beef Burgers + 2 Regular Fries + 1.5 Ltr Cold Drink', 1950, 'Deals', 'assets/burger_bomba.png') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, tag = EXCLUDED.tag, contents = EXCLUDED.contents, price = EXCLUDED.price, category = EXCLUDED.category, image = EXCLUDED.image;


-- --- Row Level Security (RLS) Configuration ---

ALTER TABLE settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE menu_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE deals ENABLE ROW LEVEL SECURITY;
ALTER TABLE reviews ENABLE ROW LEVEL SECURITY;
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;

-- 1. settings RLS Policies
CREATE POLICY "Allow public read for settings" ON settings FOR SELECT USING (true);
CREATE POLICY "Allow authenticated admin updates for settings" ON settings FOR UPDATE USING (auth.uid() IS NOT NULL);

-- 2. menu_items RLS Policies
CREATE POLICY "Allow public read for menu_items" ON menu_items FOR SELECT USING (true);
CREATE POLICY "Allow authenticated admin insert for menu_items" ON menu_items FOR INSERT WITH CHECK (auth.uid() IS NOT NULL);
CREATE POLICY "Allow authenticated admin update for menu_items" ON menu_items FOR UPDATE USING (auth.uid() IS NOT NULL);
CREATE POLICY "Allow authenticated admin delete for menu_items" ON menu_items FOR DELETE USING (auth.uid() IS NOT NULL);

-- 3. deals RLS Policies
CREATE POLICY "Allow public read for deals" ON deals FOR SELECT USING (true);
CREATE POLICY "Allow authenticated admin insert for deals" ON deals FOR INSERT WITH CHECK (auth.uid() IS NOT NULL);
CREATE POLICY "Allow authenticated admin update for deals" ON deals FOR UPDATE USING (auth.uid() IS NOT NULL);
CREATE POLICY "Allow authenticated admin delete for deals" ON deals FOR DELETE USING (auth.uid() IS NOT NULL);

-- 4. reviews RLS Policies
CREATE POLICY "Allow public read for approved reviews" ON reviews FOR SELECT USING (approved = true OR auth.uid() IS NOT NULL);
CREATE POLICY "Allow public insert for reviews" ON reviews FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow authenticated admin update/delete for reviews" ON reviews FOR ALL USING (auth.uid() IS NOT NULL);

-- 5. orders RLS Policies
CREATE POLICY "Allow public read for orders by id or phone" ON orders FOR SELECT USING (true); -- We do filtering in JS
CREATE POLICY "Allow public insert for orders" ON orders FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow authenticated admin updates for orders" ON orders FOR ALL USING (auth.uid() IS NOT NULL);

-- --- Server-Side PL/pgSQL Order capacity and pricing safety Trigger ---

CREATE OR REPLACE FUNCTION check_order_capacity_and_delivery()
RETURNS TRIGGER AS $$
DECLARE
  active_count INTEGER;
  settings_rec RECORD;
  calculated_delivery_fee NUMERIC := 0;
  item_elem JSONB;
  subtotal NUMERIC := 0;
BEGIN
  -- 1. Read settings record (id = 1)
  SELECT * INTO settings_rec FROM settings WHERE id = 1;
  IF NOT FOUND THEN
    settings_rec.max_active_orders := 50;
    settings_rec.delivery_charge_enabled := FALSE;
    settings_rec.delivery_charge_amount := 150;
  END IF;

  -- 2. Check Active Orders Capacity Limit
  SELECT COUNT(*) INTO active_count 
  FROM orders 
  WHERE status IN ('received', 'queue', 'cooking', 'packing', 'delivery');

  IF active_count >= settings_rec.max_active_orders THEN
    RAISE EXCEPTION 'We are at full capacity right now, please try again shortly'
      USING ERRCODE = 'P0001';
  END IF;

  -- 3. Calculate and Force Delivery Fee
  IF settings_rec.delivery_charge_enabled THEN
    calculated_delivery_fee := settings_rec.delivery_charge_amount;
  ELSE
    calculated_delivery_fee := 0;
  END IF;

  NEW.delivery_fee := calculated_delivery_fee;

  -- 4. Re-calculate total price to ensure it matches
  FOR item_elem IN SELECT * FROM jsonb_array_elements(NEW.items) LOOP
    subtotal := subtotal + ((item_elem->>'price')::numeric * (item_elem->>'quantity')::numeric);
  END LOOP;
  NEW.total := subtotal + NEW.delivery_fee;

  -- Force initial status to 'received' and insert start update time
  NEW.status := 'received';
  NEW.updates := jsonb_build_array(jsonb_build_object('stage', 'received', 'time', to_char(now(), 'YYYY-MM-DD"T"HH24:MI:SSOF')));
  
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_check_order_capacity_and_delivery
BEFORE INSERT ON orders
FOR EACH ROW
EXECUTE FUNCTION check_order_capacity_and_delivery();
